# JTDemo Конфигурация
# Обновлено: 2025-08-29 04:59:38
# Автор: Kostyamops

# Основные настройки
settings:
  # Показывать ли сообщения о демо-режиме другим игрокам
  # Если true, то все игроки с правом jtdemo.see-messages будут видеть уведомления
  # о входе и выходе из демо-режима
  show-demo-messages: false

  # Добавлять ли префикс к именам игроков в демо-режиме
  # Если true, то игроки в демо-режиме будут иметь префикс перед их именем
  # в чате и списке игроков
  add-demo-prefix: true

  # Префикс для игроков в демо-режиме
  # Этот текст будет добавлен перед именем игрока в демо-режиме
  demo-prefix: "[DEMO] "

  # Сообщение при входе в демо-режим
  demo-enabled-message: "§aДемо-режим включен. Используйте /jtdemo off [пароль] для выключения."

  # Сообщение при выходе из демо-режима
  demo-disabled-message: "§aДемо-режим выключен."

  # Сообщение при неверном пароле
  wrong-password-message: "§cНеверный пароль или демо-режим не активирован."

  # Сообщение о сбросе пароля
  # %player% заменяется на имя игрока
  password-reset-message: "§aПароль для %player% был сброшен на '12345'."

  # Сообщение об установке точки возрождения
  spawn-set-message: "§aТочка возрождения для демо-режима установлена на вашей текущей позиции."