name: '$NAME'
version: '$VERSION'
api-version: '$MINECRAFT_VERSION'
main: ru.joutak.template.EmptyPlugin
description: "A template plugin"
authors: ["EnderDissa", "Stunnerer", "s4dnex"]
contributors: ["technosimp"]
website: https://joutak.ru

depend: []
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:$KOTLIN_VERSION"